version: '3'
services:
<<<<<<< HEAD
    lucas_laravel:
        container_name: "lucas-pm-platform"
=======
    iker_laravel:
        container_name: "iker-pm-platform"
>>>>>>> release/1.0.0
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '100001'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-1091}:80'
            - '${VITE_PORT:-5185}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        restart: unless-stopped
networks:
    sail:
        driver: bridge
        external: true
        name: shared-network
volumes:
    sail-pgsql:
        driver: local